
TIMEOUT_REDIS_LOCK = 0.5
THROTTLE_API_DEFAULT_TIME = 100 # ms!

THROTTLE_REMAIN_SEC_TIME = 200
THROTTLE_REMAIN_MIN_TIME = 2000


LOGGING_LEVEL = 10 # DEBUG
LOGGING_FORMAT = '[%(asctime)s] (%(levelname)s) %(name)s: %(message)s'

'''
CRITICAL = 50
FATAL = CRITICAL
ERROR = 40
WARNING = 30
WARN = WARNING
INFO = 20
DEBUG = 10
NOTSET = 0
'''